version: '{branch}-{build}'

build: false

environment:
  matrix:
  - target: i686
  - target: x86_64

install:
- ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-$env:target-pc-windows-gnu.exe"
- ps: Start-FileDownload "https://static.bozaro.ru/x86_64-4.9.2-release-win32-seh-rt_v4-rev2.7z" mingw64.7z
- ps: Start-FileDownload "https://static.bozaro.ru/WixSharp.1.0.10.0.7z" WixSharp.7z
- ps: Start-FileDownload "https://github.com/bozaro/capnproto/releases/download/v0.5.1.2-pr190/capnproto-0.5.1.2-pr190.7z" capnproto.7z
- rust-nightly-%TARGET%-pc-windows-gnu.exe   /VERYSILENT /NORESTART /DIR="%APPVEYOR_BUILD_FOLDER%\rust-%TARGET%"
- 7z.exe x mingw64.7z > nul
- 7z.exe x WixSharp.7z -oWixSharp > nul
- 7z.exe x capnproto.7z -ocapnproto > nul
- SET WIXSHARP_DIR=%APPVEYOR_BUILD_FOLDER%\WixSharp\
- SET MINGW_DIR=%APPVEYOR_BUILD_FOLDER%\mingw64\
- git submodule update --init --recursive

test_script:
- SET PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\rust-%TARGET%\bin;%MINGW_DIR%\bin;%WIXSHARP_DIR%;%APPVEYOR_BUILD_FOLDER%\capnproto
- rustc -V
- cargo -V
- cargo test
- cargo build --release
- if "%TARGET%" == "i686" (copy rust-%TARGET%\bin\libgcc*.dll target\release\)
- cscs.exe wixcs\setup.cs
- nuget pack target\octobuild.nuspec -OutputDirectory target

artifacts:
- path: target/octobuild-*.msi
- path: target/octobuild-*.nupkg

deploy:
- provider: GitHub
  on:
    appveyor_repo_tag: true
  auth_token:
    secure: kDcv8Gxce2mGLKoZF9usWBmDzlUxxGLidDzKKehtPAx+m/Fbwpb7TLqbsUn8ecfv
  draft: false
  prerelease: true
- provider: NuGet
  on:
    appveyor_repo_tag: true
  server: https://www.myget.org/F/bozaro/
  api_key:
    secure: 8Xgud8TmDRF6fW3jZSI16SsDFPyYh8S/5HUCpHmeEV793APr4WT3xwFUu9HlM+eY
  artifact: /.*\.nupkg/
#- provider: NuGet
#  on:
#    appveyor_repo_tag: true
#  server: https://chocolatey.org/
#  api_key:
#    secure: 5tG16DzbxdonFS7/jYYidxVgIA8QogBVx7u0TYvikAhygXezrVWn1JKAihEnM5D7
#  artifact: /.*\.nupkg/
