[package]
name = "octobuild"
version = "0.0.5"
authors = [ "Artem V. Navrotskiy <bozaro@users.noreply.github.com>" ]
build = "src/build.rs"

[dependencies.daemon]
version = "*"

[dependencies.lz4]
version = "*"

[dependencies.xml-rs]
version = "*"

[dependencies.uuid]
version = "*"

[dependencies.tempdir]
version = "*"

[build-dependencies.capnpc]
version = "*"
